id: A53558063
base_file: fAFFB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:15:52.345037
  last_modified_at: 2022-06-05 20:15:52.345046
