id: A53558063
base_file: fE6A6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:15:52.355809
  last_modified_at: 2022-06-05 20:15:52.355830
